name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: RoyApp.sln                                 # Replace with your solution name, i.e. MyWpfApp.sln.
      Test_Project_Path: RoyAppTests\RoyAppTests.csproj         # Replace with the path to your test project, i.e. MyWpfApp.Tests\MyWpfApp.Tests.csproj.

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Begin Sonar scan
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet sonarscanner begin /o:jdubar /k:jdubar_RoyApp /d:sonar.login=${{ secrets.SONAR_TOKEN }} /d:sonar.host.url=https://sonarcloud.io
        
    - name: Build project and run unit tests
      run: |
        dotnet build ${{ env.Solution_Name }} --no-restore
        dotnet test ${{ env.Test_Project_Path }} --no-build --no-restore --verbosity normal -p:CollectCoverage=true -p:CoverletOutputFormat=opencover

    - name: End Sonar scan
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_TOKEN }}
